### ISSUE TITLE
SwiftyID @Traveloka Nov 27, 2018

### ISSUE THREAD

**Issue by ajanuar** [SwiftyID/Meetup#11]
Speaker Material:

Iqbal Ansyori, MVVM in Practice: 
[MVVMInPractive.pdf](https://github.com/SwiftyID/Meetup/files/2682244/MVVMInPractive.pdf)

Doni Ramadhan, Hot Reload in iOS:
[Hot Reload on iOS.pdf](https://github.com/SwiftyID/Meetup/files/2682246/Hot.Reload.on.iOS.pdf)

Zulwizoya Putra, Starting an Open Source Project in Swift:
[Starting an Open Source Project in Swift.pdf](https://github.com/SwiftyID/Meetup/files/2682247/Starting.an.Open.Source.Project.in.Swift.pdf)

**Comment by taufikobet** [comment]
@ajanuar thank you Albert!
